Removed django.utils six module
leplatrem/django-sizefield pull request #20
Opened 2021-08-03 09:05 UTC by Mahir-Sparkess

As of Django 3, the six module from django.utils has been removed therefore it is incompatible with Django 3.

- Removal of django.utils six module
- Update of six python 2 types to python 3 data types.

2021-08-05 16:14 UTC, leplatrem commented
@rsmith013 do you have enough permissions to merge this? What's your Pypi nickname?

2021-08-06 11:20 UTC, rsmith013 requested changes

2021-08-06 11:20 UTC, rsmith013 commented on sizefield/utils.py
> +    units_list = sorted(iter(items(FILESIZE_UNITS)), key=operator.itemgetter(1))
`FILESIZE_UNITS.items()`?

2021-08-06 11:30 UTC, rsmith013 commented
> @rsmith013 do you have enough permissions to merge this? What's your Pypi nickname?

@leplatrem just `rsmith`

2021-08-13 16:22 UTC, rsmith013 commented
This has now been taken care of in the latest release

2021-08-13 16:22 UTC, closed without merging